version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: repo_searcher
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: respository_searcher_development
volumes:
  postgres_data:
